Repository jaredpalmer/formik, pull requests merged in 2018-12, with the labels that each got.

#1163 Make validateForm internally cancellable
  .size-snapshot.json
  src/FieldArray.tsx
  src/Formik.tsx
  src/utils.ts
  src/withFormik.tsx
Labels: enhancement, in progress, priority: high

#1149 upgrade react-fast-compare to get bugfix
  package.json
Labels: in progress, pinned, priority: high

#995 Return result of field level validation
  src/Formik.tsx
Labels: pinned

#1192 Replace warning
  .size-snapshot.json
  package.json
  src/FastField.tsx
  src/Field.tsx
  src/Formik.tsx
  test/Field.test.tsx
  test/Formik.test.tsx
  types/index.d.ts
  yarn.lock
Labels: enhancement, in progress, pinned
